"""
FIFO System Implementation
-------------------------
Author: Mariano Espinoza Jimenez (E00000404309)
By_NanoEspinoza **NanoxNet_Corp** 
Version: 1.0
Created: 2024

AVISO IMPORTANTE:
- Este código es trabajo académico protegido
- No se permite su modificación o redistribución sin autorización
- El uso del código requiere mantener todas las atribuciones originales
"""

import os
import time
from datetime import datetime
import hashlib
import inspect
import re

class FIFOSystemProtected:
    """Sistema FIFO protegido para gestión de archivos."""
    
    def __init__(self, directory="fifo_files", max_files=3):
        self._verify_integrity()
        self.directory = directory
        self.max_files = max_files
        
        if not os.path.exists(directory):
            os.makedirs(directory)
    
    def _verify_integrity(self):
        """Verificación de integridad del código."""
        source = inspect.getsource(self.__class__)
        if "Mariano Espinoza Jimenez" not in source or "E00000404309" not in source:
            raise RuntimeError("ERROR: Atribución modificada o eliminada.")
    
    def create_file(self, content=""):
        self._verify_integrity()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"file_{timestamp}.txt"
        filepath = os.path.join(self.directory, filename)
        
        with open(filepath, 'w') as f:
            f.write("=" * 50 + "\n")
            f.write("Generated by FIFO System\n")
            f.write("Author: Mariano Espinoza Jimenez\n")
            f.write("Student ID: E00000404309\n")
            f.write("=" * 50 + "\n\n")
            f.write(f"Archivo creado: {timestamp}\n")
            f.write(content)
        
        print(f"Archivo creado: {filename}")
        self.check_and_remove_oldest()
    
    def check_and_remove_oldest(self):
        self._verify_integrity()
        files = self.get_files_sorted()
        
        while len(files) > self.max_files:
            oldest_file = files[0]
            oldest_path = os.path.join(self.directory, oldest_file)
            os.remove(oldest_path)
            print(f"Archivo más antiguo eliminado: {oldest_file}")
            files = self.get_files_sorted()
    
    def get_files_sorted(self):
        self._verify_integrity()
        files = os.listdir(self.directory)
        files.sort()
        return files
    
    def list_files(self):
        self._verify_integrity()
        files = self.get_files_sorted()
        print("\nArchivos actuales:")
        for file in files:
            filepath = os.path.join(self.directory, file)
            timestamp = os.path.getctime(filepath)
            datetime_str = datetime.fromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S')
            print(f"{file} - Creado: {datetime_str}")

# Ejemplo de uso
if __name__ == "__main__":
    print("Sistema FIFO - Demostración")
    print("Autor: Mariano Espinoza Jimenez")
    print("ID: E00000404309")
    print("-" * 50)
    
    fifo = FIFOSystemProtected()
    
    # Crear algunos archivos de prueba
    for i in range(5):
        print(f"\nCreando archivo {i+1}...")
        fifo.create_file(f"Contenido del archivo {i+1}")
        fifo.list_files()
        time.sleep(1)